### ISSUE TITLE
courseX 某些中文课程无法通过中文课程名搜索

### ISSUE THREAD

**Issue by liang2kl** [robertying/thursday#2]
例如：https://tsinghua.app/courses?q=徐帆 中的 Advanced Topics in Linear Algebra，是中文课程，中文课程名应为《高等线性代数选讲》，但无法使用课程名搜到。

这种情况导致某些不知道情况的同学难以搜到对应的课程。

**Comment by robertying** [comment]
这是一个已知问题。learnX 现在拉取课程信息根据系统语言，如果有同学使用英文并且开启 courseX 上传，课程名会用英文，中文名不会被记录，导致了这个问题。

让我看看还能不能同时拉取中英名称。

**Comment by robertying** [comment]
tsinghua.app 已开启英文课程名显示和搜索，learnX 端的上传会在新版本更新。
